### ISSUE TITLE
New Windows UI - v2

### ISSUE THREAD

**Issue by NghiaTranUIT** [ProxymanApp/proxyman-windows-linux#306]
## Description
#305 should be deprecated.

The new design looks better, but it's hard to use: For example:

New Design:
- Status View is hidden -> Need to click to show the Popover 
- Content Type Filter (JSON, HTTP, HTTPS, ...) is hidden -> Need to click on the Filter button to show it -> Hard to discover

### Task 1: Use the new menu from Shadcn
- [ ] Install the Shadcn for the Menu Context. Code: https://ui.shadcn.com/examples/music
- [ ] Replace the main app menu (BlueprintJS) with a new menu from ShadCN, including Proxyman, File, Edit, Certificate, Diff....

<img width="508" alt="Screenshot 2023-09-24 at 16 50 25" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/8f129da6-6d6e-4715-b667-cf596b6892fb">

- [ ] Make sure all Shortcuts are still working (For example Control + , -> Show the Preference)

<img width="310" alt="Screenshot 2023-09-24 at 16 52 25" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/6c818e72-3b98-4844-ba6f-f35196c875d7">

- [ ] Replace the menu context from the Main Table View -> Make sure all shortcuts are working ✅ 
<img width="298" alt="Screenshot 2023-09-24 at 16 54 37" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/532a2053-c200-47fa-a9b6-2652ac2d5cf1">

- [ ] Replace the menu context from the Left pane

<img width="458" alt="Screenshot 2023-09-24 at 16 52 38" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/a9807cdd-c6cb-4ddd-9980-d69af271f486">

- [ ] Replace all menu context from All tools: Map Local, Breakpoint, Diff, ...

<img width="443" alt="Screenshot 2023-09-24 at 16 56 02" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/6210ffac-d9af-4e09-9160-212eda4c02bc">

**Comment by NghiaTranUIT** [comment]
### Task 2: Place Dropdown with ShadCN
-  [ ] Replace old dropdown from the Filter (e.g. URL and Contains dropdown) with ShadCN
<img width="458" alt="Screenshot 2023-09-24 at 16 52 57" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/64baf2d3-fa03-49b5-a8ed-a1c2c909df0f">

- [ ] Make sure we keep the current size of the two buttons (width, height)
- [ ] Replace the checkbox with ShadCN checkbox button (Make sure same width/height)

**Comment by NghiaTranUIT** [comment]
### Task 3: Use Shadcn Popover
- [ ] Remove all BlueprintJS Dialog code (When displaying the Preference, Certificate View, iOS device, Android, ...)
- [ ] Use ShadCN Popover 
- [ ] Make sure all UI of theses screens are not broken 

### Task 4: Replace BlueprintJS buttons with shadcn button
- [ ] The problem of the BlueprintJS button is it has shadow -> Replace BlueprintJS button with shadcn button
- [ ] Make sure it has the same width and height, font size, font name
- [ ] Use default Shadcn border color and border radius.
- [ ] Find all buttons from the app and replace it.

For example:
<img width="238" alt="Screenshot 2023-09-24 at 17 02 31" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/cf133aec-1c4e-4017-9f85-855bf8caac51">



<img width="799" alt="Screenshot 2023-09-24 at 17 05 21" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/f9c8ca3c-59e1-4a4a-a523-e6b80b5701bd">
<img width="213" alt="Screenshot 2023-09-24 at 17 05 31" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/b98d46f2-6308-4d20-9969-f3c8e3c4ab32">
<img width="556" alt="Screenshot 2023-09-24 at 17 05 50" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/a7d3f1c6-6870-4683-9416-8e2d816f46c8">
<img width="317" alt="Screenshot 2023-09-24 at 17 06 03" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/56f9e93e-4446-4737-90ad-62742c8b6d1b">
<img width="157" alt="Screenshot 2023-09-24 at 17 06 09" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/c62b893b-894e-4412-9290-4446545d5729">
<img width="177" alt="Screenshot 2023-09-24 at 17 06 17" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/eec7109a-fe71-4299-8347-bb2f680cd74f">

**Comment by NghiaTranUIT** [comment]
### Task 5: Replace BlueprintJS Alert 
- [ ] Replace all BlueprintJS Alert with ShadCN: https://ui.shadcn.com/docs/components/alert-dialog
- [ ] Don't use any ICON.

For example:
<img width="445" alt="Screenshot 2023-09-24 at 17 06 39" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/19c0954c-97dc-471e-8193-ee4dcbb7d5ae">

- [ ] Make sure the Title and description are intact. The destruction button should have a Red Background
- [ ] Logic is still working

**Comment by NghiaTranUIT** [comment]
### Task 6: Replace BlueprintJS Toast
- [ ] Find all Toast and replace with shadcn toast: https://ui.shadcn.com/docs/components/toast

- [ ] Premium Toast: Find a way to show a Toast in the same position as the current Toast (Top Middle). Make sure to have `Upgrade Now` button

<img width="550" alt="Screenshot 2023-09-24 at 17 13 15" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/f5e89d98-eb69-40cb-b576-a838667bba98">

- [ ] Error Toast: Show Destructive Toast (Right Bottom position) with the error -> Make sure current buttons are working.

**Comment by NghiaTranUIT** [comment]
### Task 7: Replace Header Table View with new Header from Windows-Prototype
- [ ] Remove the old Header (as a Table View with 2 columns) to the new Header from Windows-Prototype -> It means we can easily select text from multiple rows.
- [ ] Has two Columns: Key & Value
- [ ] Verify the Header Filter is working
- [ ] Apply to the Form, Query, Auth, ... which uses the Header View

**Comment by NghiaTranUIT** [comment]
### Task 8: Improve the Summary tab
- [ ] Remove the Expand/Collapse Animation
- [ ] Fix the height of the row: Currently, it's too big, and it's inconsistent with the Height of the Header Row => Use the same Height as the Header Row

<img width="535" alt="Screenshot 2023-09-25 at 08 47 12" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/1ec0e9ee-57c2-41c5-9729-7d1cf80872f7">

**Comment by NghiaTranUIT** [comment]
### Task 9: Redesign the Update App panel
- [ ] Remove old code that shows this Window Panel when there is a new update, updating the app, installing the new update, ..

<img width="440" alt="Screenshot 2023-09-25 at 08 53 20" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/f4182d77-86fc-4648-be5a-b30e18c86f82">

<img width="435" alt="Screenshot 2023-09-25 at 08 51 26" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/e4a73236-ecf6-4eb2-a9c3-c45c0bfc7a08">

- [ ] Implement new design => ⚠️ Design will provide in this week.

**Comment by NghiaTranUIT** [comment]
### Task 10: Some improvement
- [ ] The Badge button is not horizontally aligned with the Status View. Look at the Top and Bottom Padding. => Increase the size of the Status Bar 1 or 2 px, or more. Fix these badge buttons -> Make it horizontally aligned. => Make sure it looks better.

![Screenshot 2023-09-25 at 08 52 48](https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/7d5b2239-d478-41f5-8ed4-1a2541f5080e)

**Comment by NghiaTranUIT** [comment]
Updated: new design for `Task 9: Redesign the Update App panel`

**Comment by NghiaTranUIT** [comment]
### Task 11: Update new design for Change Logs
- Use Shadcn dialog: https://ui.shadcn.com/docs/components/dialog
- Design similar (Title, Description, font size, font weight) with:

<img width="510" alt="Screenshot 2023-09-27 at 08 49 30" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/297947f0-be5b-45f3-8779-3085f845d927">

- Title: Proxyman Change Logs
- Description: Proxyman {version} is available to update.
- Content: Use the Markdown render, corner border -> Make sure the padding looks good. The current design is off.  
- Use one button: Install as a Primary Button (Black)

<img width="922" alt="Screenshot 2023-09-27 at 08 41 50" src="https://github.com/ProxymanApp/proxyman-windows-linux/assets/5878421/6dd0b84e-96eb-4d93-9dde-ebb577693bb4">
